[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "poyaohuang", email = "poyaohg0705@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.19.2",
    "datasets>=5.0.1",
    "fastapi[standard]>=0.141.1",
    "greenlet>=3.5.5",
    "logging>=0.4.9.6",
    "pgvector>=0.5.0",
    "psycopg[binary]>=3.3.5",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-dotenv>=1.2.3",
    "sqlalchemy[asyncio]>=2.0.52",
    "sqlmodel>=0.0.42",
]

[project.scripts]
backend = "backend:main"
ingest = "backend.scripts.ingestion:main"
build-passages = "backend.scripts.passages:main"

[tool.fastapi]
entrypoint = "backend.main:app"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
